# Generated by Django 4.2.5 on 2023-12-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0005_file_deleted_file_deleted_at_file_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
