# Generated by Django 4.2.5 on 2023-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0007_sharedfile_shared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
