# Generated by Django 4.2.5 on 2023-12-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0009_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
