# Generated by Django 4.2.5 on 2023-12-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0010_sharedfile_shared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
